version: '3.3'
services:
  hbb-health-db:
    container_name: hbb-health-db
    build:
      context: ./db
    ports:
      - "5433:5432"
    networks:
      - lndnet

  hbb-health:
    container_name: hbb-health
    build:
      context: ./
    environment:
      - DB_HOST=hbb-health-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_DATABASE=postgres
      - DB_PORT=5433

    ports:
      - "3002:3000"
    networks:
      - lndnet
    depends_on:
      - "hbb-health-db"

networks:
  lndnet:
    driver: bridge